check_in:
  cron: "*/30 * * * *" # execute at every 30 minutes
  class: "AllLeetcodeUserCheckinJob"
#  queue: hard_worker_long
#  args:
#    hard: "stuff"
# Reference: https://github.com/ondrejbartas/sidekiq-cron

daily_report:
  cron: "0 6 * * *" # execute at 6.00 am every day
  class: "DailyReportJob"